In [1]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import LabelEncoder
import numpy as np
import pandas as pd
df=pd.read_csv("CarPrice_Assignment.csv")
kk=pd.read_csv("CarPrice_Assignment.csv")
df

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,202,-1,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,203,-1,volvo 244dl,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,204,-1,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,205,-1,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

In [2]:
df["CarName"].unique()

array(['alfa-romero giulia', 'alfa-romero stelvio',
       'alfa-romero Quadrifoglio', 'audi 100 ls', 'audi 100ls',
       'audi fox', 'audi 5000', 'audi 4000', 'audi 5000s (diesel)',
       'bmw 320i', 'bmw x1', 'bmw x3', 'bmw z4', 'bmw x4', 'bmw x5',
       'chevrolet impala', 'chevrolet monte carlo', 'chevrolet vega 2300',
       'dodge rampage', 'dodge challenger se', 'dodge d200',
       'dodge monaco (sw)', 'dodge colt hardtop', 'dodge colt (sw)',
       'dodge coronet custom', 'dodge dart custom',
       'dodge coronet custom (sw)', 'honda civic', 'honda civic cvcc',
       'honda accord cvcc', 'honda accord lx', 'honda civic 1500 gl',
       'honda accord', 'honda civic 1300', 'honda prelude',
       'honda civic (auto)', 'isuzu MU-X', 'isuzu D-Max ',
       'isuzu D-Max V-Cross', 'jaguar xj', 'jaguar xf', 'jaguar xk',
       'maxda rx3', 'maxda glc deluxe', 'mazda rx2 coupe', 'mazda rx-4',
       'mazda glc deluxe', 'mazda 626', 'mazda glc', 'mazda rx-7 gs',
       'mazda glc 4', 'mazda glc custom l', 'mazda glc custom',
       'buick electra 225 custom', 'buick century luxus (sw)',
       'buick century', 'buick skyhawk', 'buick opel isuzu deluxe',
       'buick skylark', 'buick century special',
       'buick regal sport coupe (turbo)', 'mercury cougar',
       'mitsubishi mirage', 'mitsubishi lancer', 'mitsubishi outlander',
       'mitsubishi g4', 'mitsubishi mirage g4', 'mitsubishi montero',
       'mitsubishi pajero', 'Nissan versa', 'nissan gt-r', 'nissan rogue',
       'nissan latio', 'nissan titan', 'nissan leaf', 'nissan juke',
       'nissan note', 'nissan clipper', 'nissan nv200', 'nissan dayz',
       'nissan fuga', 'nissan otti', 'nissan teana', 'nissan kicks',
       'peugeot 504', 'peugeot 304', 'peugeot 504 (sw)', 'peugeot 604sl',
       'peugeot 505s turbo diesel', 'plymouth fury iii',
       'plymouth cricket', 'plymouth satellite custom (sw)',
       'plymouth fury gran sedan', 'plymouth valiant', 'plymouth duster',
       'porsche macan', 'porcshce panamera', 'porsche cayenne',
       'porsche boxter', 'renault 12tl', 'renault 5 gtl', 'saab 99e',
       'saab 99le', 'saab 99gle', 'subaru', 'subaru dl', 'subaru brz',
       'subaru baja', 'subaru r1', 'subaru r2', 'subaru trezia',
       'subaru tribeca', 'toyota corona mark ii', 'toyota corona',
       'toyota corolla 1200', 'toyota corona hardtop',
       'toyota corolla 1600 (sw)', 'toyota carina', 'toyota mark ii',
       'toyota corolla', 'toyota corolla liftback',
       'toyota celica gt liftback', 'toyota corolla tercel',
       'toyota corona liftback', 'toyota starlet', 'toyota tercel',
       'toyota cressida', 'toyota celica gt', 'toyouta tercel',
       'vokswagen rabbit', 'volkswagen 1131 deluxe sedan',
       'volkswagen model 111', 'volkswagen type 3', 'volkswagen 411 (sw)',
       'volkswagen super beetle', 'volkswagen dasher', 'vw dasher',
       'vw rabbit', 'volkswagen rabbit', 'volkswagen rabbit custom',
       'volvo 145e (sw)', 'volvo 144ea', 'volvo 244dl', 'volvo 245',
       'volvo 264gl', 'volvo diesel', 'volvo 246'], dtype=object)

In [3]:
#df.columns

In [4]:
df[['CarName','fueltype', 'aspiration','doornumber', 'carbody', 'drivewheel', 'enginelocation','fuelsystem','enginetype','cylindernumber']] = df[[ 'CarName','fueltype', 'aspiration','doornumber', 'carbody', 'drivewheel', 'enginelocation','fuelsystem','enginetype','cylindernumber']].apply(LabelEncoder().fit_transform)

In [5]:
df

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,2,1,0,1,0,2,0,88.6,...,130,5,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,3,1,0,1,0,2,0,88.6,...,130,5,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,1,1,0,1,2,2,0,94.5,...,152,5,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,4,1,0,0,3,1,0,99.8,...,109,5,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,5,1,0,0,3,0,0,99.4,...,136,5,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,139,1,0,0,3,2,0,109.1,...,141,5,3.78,3.15,9.5,114,5400,23,28,16845.0
201,202,-1,138,1,1,0,3,2,0,109.1,...,141,5,3.78,3.15,8.7,160,5300,19,25,19045.0
202,203,-1,140,1,0,0,3,2,0,109.1,...,173,5,3.58,2.87,8.8,134,5500,18,23,21485.0
203,204,-1,142,0,1,0,3,2,0,109.1,...,145,3,3.01,3.40,23.0,106,4800,26,27,22470.0
204,205,-1,143,1,1,0,3,2,0,109.1,...,141,5,3.78,3.15,9.5,114,5400,19,25,22625.0

In [6]:
import pandas as pd
import numpy as np


# Function to remove outliers using Z-score
def remove_outliers(df, columns, threshold=3):
    z_scores = np.abs((df[columns] - df[columns].mean()) / df[columns].std())
    df_no_outliers = df[(z_scores < threshold).all(axis=1)]
    return df_no_outliers

# Specify columns for outlier removal
columns_to_check = ['drivewheel','wheelbase','carlength','carwidth','curbweight','enginesize',
'fuelsystem'
,'boreratio',
'horsepower',
'citympg',
'highwaympg']

# Remove outliers
df_no_outliers = remove_outliers(df, columns_to_check)

print("Original DataFrame:")
print(df)
print("\nDataFrame without outliers:")
print(df_no_outliers)

Original DataFrame:
     car_ID  symboling  CarName  fueltype  aspiration  doornumber  carbody  \
0         1          3        2         1           0           1        0
1         2          3        3         1           0           1        0
2         3          1        1         1           0           1        2
3         4          2        4         1           0           0        3
4         5          2        5         1           0           0        3
..      ...        ...      ...       ...         ...         ...      ...
200     201         -1      139         1           0           0        3
201     202         -1      138         1           1           0        3
202     203         -1      140         1           0           0        3
203     204         -1      142         0           1           0        3
204     205         -1      143         1           1           0        3

     drivewheel  enginelocation  wheelbase  ...  enginesize  fuelsystem  \
0             2               0       88.6  ...         130           5
1             2               0       88.6  ...         130           5
2             2               0       94.5  ...         152           5
3             1               0       99.8  ...         109           5
4             0               0       99.4  ...         136           5
..          ...             ...        ...  ...         ...         ...
200           2               0      109.1  ...         141           5
201           2               0      109.1  ...         141           5
202           2               0      109.1  ...         173           5
203           2               0      109.1  ...         145           3
204           2               0      109.1  ...         141           5

     boreratio  stroke  compressionratio  horsepower  peakrpm  citympg  \
0         3.47    2.68               9.0         111     5000       21
1         3.47    2.68               9.0         111     5000       21
2         2.68    3.47               9.0         154     5000       19
3         3.19    3.40              10.0         102     5500       24
4         3.19    3.40               8.0         115     5500       18
..         ...     ...               ...         ...      ...      ...
200       3.78    3.15               9.5         114     5400       23
201       3.78    3.15               8.7         160     5300       19
202       3.58    2.87               8.8         134     5500       18
203       3.01    3.40              23.0         106     4800       26
204       3.78    3.15               9.5         114     5400       19

     highwaympg    price
0            27  13495.0
1            27  16500.0
2            26  16500.0
3            30  13950.0
4            22  17450.0
..          ...      ...
200          28  16845.0
201          25  19045.0
202          23  21485.0
203          27  22470.0
204          25  22625.0

[205 rows x 26 columns]

DataFrame without outliers:
     car_ID  symboling  CarName  fueltype  aspiration  doornumber  carbody  \
0         1          3        2         1           0           1        0
1         2          3        3         1           0           1        0
2         3          1        1         1           0           1        2
3         4          2        4         1           0           0        3
4         5          2        5         1           0           0        3
..      ...        ...      ...       ...         ...         ...      ...
200     201         -1      139         1           0           0        3
201     202         -1      138         1           1           0        3
202     203         -1      140         1           0           0        3
203     204         -1      142         0           1           0        3
204     205         -1      143         1           1           0        3

     drivewheel  enginelocation  wheelbase  ...  enginesize  fuelsystem  \
0             2               0       88.6  ...         130           5
1             2               0       88.6  ...         130           5
2             2               0       94.5  ...         152           5
3             1               0       99.8  ...         109           5
4             0               0       99.4  ...         136           5
..          ...             ...        ...  ...         ...         ...
200           2               0      109.1  ...         141           5
201           2               0      109.1  ...         141           5
202           2               0      109.1  ...         173           5
203           2               0      109.1  ...         145           3
204           2               0      109.1  ...         141           5

     boreratio  stroke  compressionratio  horsepower  peakrpm  citympg  \
0         3.47    2.68               9.0         111     5000       21
1         3.47    2.68               9.0         111     5000       21
2         2.68    3.47               9.0         154     5000       19
3         3.19    3.40              10.0         102     5500       24
4         3.19    3.40               8.0         115     5500       18
..         ...     ...               ...         ...      ...      ...
200       3.78    3.15               9.5         114     5400       23
201       3.78    3.15               8.7         160     5300       19
202       3.58    2.87               8.8         134     5500       18
203       3.01    3.40              23.0         106     4800       26
204       3.78    3.15               9.5         114     5400       19

     highwaympg    price
0            27  13495.0
1            27  16500.0
2            26  16500.0
3            30  13950.0
4            22  17450.0
..          ...      ...
200          28  16845.0
201          25  19045.0
202          23  21485.0
203          27  22470.0
204          25  22625.0

[196 rows x 26 columns]

In [7]:
df_no_outliers

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,2,1,0,1,0,2,0,88.6,...,130,5,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,3,1,0,1,0,2,0,88.6,...,130,5,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,1,1,0,1,2,2,0,94.5,...,152,5,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,4,1,0,0,3,1,0,99.8,...,109,5,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,5,1,0,0,3,0,0,99.4,...,136,5,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,139,1,0,0,3,2,0,109.1,...,141,5,3.78,3.15,9.5,114,5400,23,28,16845.0
201,202,-1,138,1,1,0,3,2,0,109.1,...,141,5,3.78,3.15,8.7,160,5300,19,25,19045.0
202,203,-1,140,1,0,0,3,2,0,109.1,...,173,5,3.58,2.87,8.8,134,5500,18,23,21485.0
203,204,-1,142,0,1,0,3,2,0,109.1,...,145,3,3.01,3.40,23.0,106,4800,26,27,22470.0
204,205,-1,143,1,1,0,3,2,0,109.1,...,141,5,3.78,3.15,9.5,114,5400,19,25,22625.0

In [8]:
df_no_outliers["cylindernumber"]

0      2
1      2
2      3
3      2
4      1
      ..
200    2
201    2
202    3
203    3
204    2
Name: cylindernumber, Length: 196, dtype: int32

df_no_outliers.isnull().sum()

In [9]:
cor=df_no_outliers.corr()
cor

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
car_ID,1.000000,-0.153998,0.970833,-0.124371,0.054356,-0.186857,0.096650,0.066013,0.048541,0.161948,...,0.024062,0.209350,0.274726,-0.150104,0.152117,0.002247,-0.235183,0.042278,0.026965,-0.086019
symboling,-0.153998,1.000000,-0.111080,0.204018,-0.061701,0.669043,-0.596475,-0.022266,0.214189,-0.543251,...,-0.063550,0.117557,-0.108591,0.007425,-0.189066,0.132404,0.274525,-0.104075,-0.023925,-0.044398
CarName,0.970833,-0.111080,1.000000,-0.063245,0.003869,-0.169564,0.091842,0.004353,0.052895,0.061147,...,-0.098827,0.133887,0.216004,-0.175665,0.096293,-0.075678,-0.177202,0.111756,0.109289,-0.201214
fueltype,-0.124371,0.204018,-0.063245,1.000000,-0.414795,0.214050,-0.143293,-0.158516,0.040848,-0.375436,...,-0.147936,0.037405,-0.088814,-0.258229,-0.985513,0.149750,0.494221,-0.243335,-0.169586,-0.173065
aspiration,0.054356,-0.061701,0.003869,-0.414795,1.000000,-0.022582,0.059949,0.082104,-0.060143,0.304427,...,0.203724,0.301497,0.236511,0.249156,0.306766,0.322813,-0.199014,-0.232683,-0.295082,0.254816
doornumber,-0.186857,0.669043,-0.169564,0.214050,-0.022582,1.000000,-0.684161,0.109127,0.143963,-0.456385,...,-0.027344,0.029295,-0.113457,0.047909,-0.208446,0.136216,0.255957,-0.043581,-0.017065,-0.038787
carbody,0.096650,-0.596475,0.091842,-0.143293,0.059949,-0.684161,1.000000,-0.159884,-0.282464,0.438957,...,-0.091787,-0.073503,0.017273,-0.028178,0.131534,-0.175246,-0.115326,0.051326,0.006161,-0.082159
drivewheel,0.066013,-0.022266,0.004353,-0.158516,0.082104,0.109127,-0.159884,1.000000,0.155187,0.431715,...,0.524933,0.403442,0.450965,0.050032,0.153235,0.495969,-0.025284,-0.427896,-0.429277,0.561766
enginelocation,0.048541,0.214189,0.052895,0.040848,-0.060143,0.143963,-0.282464,0.155187,1.000000,-0.203413,...,0.276769,0.109758,0.198116,-0.143139,-0.019724,0.385100,0.199381,-0.176077,-0.117505,0.395888
wheelbase,0.161948,-0.543251,0.061147,-0.375436,0.304427,-0.456385,0.438957,0.431715,-0.203413,1.000000,...,0.490024,0.351915,0.441648,0.104186,0.322187,0.279966,-0.352208,-0.388723,-0.466135,0.502011
carlength,0.194816,-0.342239,0.087009,-0.262024,0.272252,-0.403566,0.357186,0.458632,-0.052929,0.855822,...,0.656224,0.538704,0.572653,0.084686,0.209710,0.519758,-0.280533,-0.617632,-0.648806,0.644308
carwidth,0.069665,-0.219184,-0.051979,-0.307486,0.367417,-0.232593,0.160711,0.431324,-0.051639,0.793791,...,0.684280,0.505643,0.497984,0.172355,0.246338,0.550082,-0.222639,-0.593415,-0.637735,0.703097
carheight,0.251880,-0.561754,0.210762,-0.288776,0.081170,-0.556277,0.594423,-0.007333,-0.111772,0.641679,...,0.141138,0.018763,0.189394,-0.073478,0.277321,-0.059168,-0.324283,-0.057454,-0.119472,0.170253
curbweight,0.109208,-0.202332,-0.012183,-0.292395,0.399456,-0.200594,0.138616,0.550867,0.064647,0.747656,...,0.835202,0.608088,0.616126,0.122562,0.217736,0.713779,-0.264092,-0.732906,-0.777027,0.800995
enginetype,-0.095964,0.053161,-0.088957,0.097293,-0.120360,0.046153,-0.028287,-0.119927,0.122170,-0.164817,...,0.023720,-0.098421,0.040313,-0.067206,-0.089605,0.031802,0.024109,-0.094275,-0.070404,0.056184
cylindernumber,-0.007151,0.228570,0.057880,0.124822,-0.150539,0.173285,-0.092576,0.278752,0.152321,-0.156819,...,-0.076683,0.037643,0.037858,-0.050749,-0.087357,0.203283,0.250143,-0.220888,-0.162306,0.042085
enginesize,0.024062,-0.063550,-0.098827,-0.147936,0.203724,-0.027344,-0.091787,0.524933,0.276769,0.490024,...,1.000000,0.550399,0.579896,0.193193,0.089895,0.797774,-0.235047,-0.654045,-0.665244,0.831674
fuelsystem,0.209350,0.117557,0.133887,0.037405,0.301497,0.029295,-0.073503,0.403442,0.109758,0.351915,...,0.550399,1.000000,0.448907,0.075075,-0.097742,0.685492,0.022682,-0.681933,-0.651611,0.528936
boreratio,0.274726,-0.108591,0.216004,-0.088814,0.236511,-0.113457,0.017273,0.450965,0.198116,0.441648,...,0.579896,0.448907,1.000000,-0.088758,0.037758,0.529160,-0.265307,-0.540057,-0.547249,0.505474
stroke,-0.150104,0.007425,-0.175665,-0.258229,0.249156,0.047909,-0.028178,0.050032,-0.143139,0.104186,...,0.193193,0.075075,-0.088758,1.000000,0.210966,0.081126,-0.039136,-0.020577,-0.013619,0.026231
compressionratio,0.152117,-0.189066,0.096293,-0.985513,0.306766,-0.208446,0.131534,0.153235,-0.019724,0.322187,...,0.089895,-0.097742,0.037758,0.210966,1.000000,-0.211576,-0.456086,0.320133,0.250235,0.128588
horsepower,0.002247,0.132404,-0.075678,0.149750,0.322813,0.136216,-0.175246,0.495969,0.385100,0.279966,...,0.797774,0.685492,0.529160,0.081126,-0.211576,1.000000,0.167832,-0.831059,-0.800396,0.782479
peakrpm,-0.235183,0.274525,-0.177202,0.494221,-0.199014,0.255957,-0.115326,-0.025284,0.199381,-0.352208,...,-0.235047,0.022682,-0.265307,-0.039136,-0.456086,0.167832,1.000000,-0.139003,-0.085954,-0.038761
citympg,0.042278,-0.104075,0.111756,-0.243335,-0.232683,-0.043581,0.051326,-0.427896,-0.176077,-0.388723,...,-0.654045,-0.681933,-0.540057,-0.020577,0.320133,-0.831059,-0.139003,1.000000,0.966435,-0.679668
highwaympg,0.026965,-0.023925,0.109289,-0.169586,-0.295082,-0.017065,0.006161,-0.429277,-0.117505,-0.466135,...,-0.665244,-0.651611,-0.547249,-0.013619,0.250235,-0.800396,-0.085954,0.966435,1.000000,-0.681772
price,-0.086019,-0.044398,-0.201214,-0.173065,0.254816,-0.038787,-0.082159,0.561766,0.395888,0.502011,...,0.831674,0.528936,0.505474,0.026231,0.128588,0.782479,-0.038761,-0.679668,-0.681772,1.000000

In [10]:
cor_target=abs(cor["price"])
cor_target

car_ID              0.086019
symboling           0.044398
CarName             0.201214
fueltype            0.173065
aspiration          0.254816
doornumber          0.038787
carbody             0.082159
drivewheel          0.561766
enginelocation      0.395888
wheelbase           0.502011
carlength           0.644308
carwidth            0.703097
carheight           0.170253
curbweight          0.800995
enginetype          0.056184
cylindernumber      0.042085
enginesize          0.831674
fuelsystem          0.528936
boreratio           0.505474
stroke              0.026231
compressionratio    0.128588
horsepower          0.782479
peakrpm             0.038761
citympg             0.679668
highwaympg          0.681772
price               1.000000
Name: price, dtype: float64

In [11]:
cor_target=abs(cor["price"])
relevant_features = cor_target[cor_target>0.5]
relevant_features

drivewheel    0.561766
wheelbase     0.502011
carlength     0.644308
carwidth      0.703097
curbweight    0.800995
enginesize    0.831674
fuelsystem    0.528936
boreratio     0.505474
horsepower    0.782479
citympg       0.679668
highwaympg    0.681772
price         1.000000
Name: price, dtype: float64

In [31]:
x=df_no_outliers[['CarName', 'fueltype', 
       'doornumber', 'carbody', 'drivewheel', 'enginelocation', 'wheelbase',
         'curbweight', 'enginetype',
        'enginesize','boreratio', 'stroke',
        'horsepower', 'peakrpm', 'citympg', 'highwaympg']]
y=df_no_outliers["price"]
x

,CarName,fueltype,doornumber,carbody,drivewheel,enginelocation,wheelbase,curbweight,enginetype,enginesize,boreratio,stroke,horsepower,peakrpm,citympg,highwaympg
0,2,1,1,0,2,0,88.6,2548,0,130,3.47,2.68,111,5000,21,27
1,3,1,1,0,2,0,88.6,2548,0,130,3.47,2.68,111,5000,21,27
2,1,1,1,2,2,0,94.5,2823,5,152,2.68,3.47,154,5000,19,26
3,4,1,0,3,1,0,99.8,2337,3,109,3.19,3.40,102,5500,24,30
4,5,1,0,3,0,0,99.4,2824,3,136,3.19,3.40,115,5500,18,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,139,1,0,3,2,0,109.1,2952,3,141,3.78,3.15,114,5400,23,28
201,138,1,0,3,2,0,109.1,3049,3,141,3.78,3.15,160,5300,19,25
202,140,1,0,3,2,0,109.1,3012,5,173,3.58,2.87,134,5500,18,23
203,142,0,0,3,2,0,109.1,3217,3,145,3.01,3.40,106,4800,26,27
204,143,1,0,3,2,0,109.1,3062,3,141,3.78,3.15,114,5400,19,25

In [32]:
y.shape

(196,)

In [33]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [46]:
model=LinearRegression(learning_rate=0.001, n_iterations=1000)
model.fit(X_train,y_train)

TypeError: LinearRegression.__init__() got an unexpected keyword argument 'learning_rate'

In [35]:
y_p=model.predict(X_test)
y_p

array([ 8856.77618109,  6152.17005732, 25977.48909101, 14332.87496421,
        5055.70079142, 15348.71222478,  6308.66803284, 10574.39463267,
        7829.77430422, 17841.41167609,  8070.26356641, 26709.8391299 ,
       13012.08180032, 17378.82808086, 10600.23818083,  7227.31848051,
        4703.18659439, 19646.52335213, 11620.53033813, 15250.95273565,
        7148.80575161, 21506.48688988, 10387.06046375,  5464.39748117,
        5260.34336847, 28134.02061507, 15120.28864685,  7198.54193866,
        6183.60970884, 19871.52614817,  7082.65712148, 34155.08188507,
       10043.74566078,  7946.91590991,  8449.82024887, 21282.02554227,
       10419.04814151,  8014.3806026 ,  8560.75609406, 14718.48410087])

In [43]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np



# Calculate Mean Absolute Error (MAE)
mae = mean_absolute_error(y_test, y_p)
print("Mean Absolute Error (MAE):", mae)

# Calculate Mean Squared Error (MSE)
mse = mean_squared_error(y_test, y_p)
print("Mean Squared Error (MSE):", mse)

# Calculate R-squared (R^2)
r2 = r2_score(y_test, y_p)
print("R-squared (R^2):", r2)

Mean Absolute Error (MAE): 2308.6652336806337
Mean Squared Error (MSE): 13267690.871781243
R-squared (R^2): 0.8164626321328725

In [37]:
joblib.dump(model,"car_price.joblib")

['car_price.joblib']

In [38]:
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

In [39]:
import joblib

In [40]:
y_test

148     8013.000
121     6692.000
16     41315.000
82     12629.000
163     8058.000
194    12940.000
76      5389.000
60      8495.000
19      6295.000
178    16558.000
165     9298.000
15     30760.000
170    11199.000
65     18280.000
123     8921.000
122     7609.000
154     7898.000
9      17859.167
80      9959.000
196    15985.000
120     6229.000
101    13499.000
147    10198.000
50      5195.000
93      7349.000
72     35056.000
137    18620.000
182     7775.000
32      5399.000
75     16503.000
89      5499.000
127    34028.000
192    13845.000
25      6692.000
146     7463.000
103    13499.000
61     10595.000
20      6575.000
131     9895.000
83     14869.000
Name: price, dtype: float64

In [41]:
C=joblib.load("car_price.joblib")

In [22]:
input_data=(3,1,1,0,2,0,88.6,2548,0,130,3.47,2.68,111,5500,21,27,)
input_data_as_numpy_array=np.asarray(input_data)
input_data_reshaped=input_data_as_numpy_array.reshape(1,-1)
result=C.predict(input_data_reshaped)
print(result)

[14787.59412786]

C:\Users\LENOVO\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

x